### ISSUE TITLE
interact() by default

### ISSUE THREAD

**Issue by sttawm** [mapsense/mapsense.js#11]
If interaction is added to the map by default, we need a way to disable it.
One approach involves storing a reference to the `interact` object and providing a getter/setter

```js
ms.map = function() {
    var map = {},
        ...
        interact = ms.interact();

    add(interact);

    map.interact = function(x) { 
        if (!arguments.length) return interact;
        interact.add(x? map : null);
    }

    ...
};

// disable interact
map.interact(false);
```

Could also just have a plain getter and do:

```js
ms.map = function() {
    var map = {},
        ...
        interact = ms.interact();

    add(interact);

    map.interact = function() {  return interact; }
    ...
};

// disable interact
map.remove(map.interact());
```

These don't seem so bad, and are simple enough. `map.add(ms.interact())` is probably common enough that automating it is worth it.

Thoughts?
    
.

**Comment by mpruett** [comment]
Done.
